# Generated by Django 4.2.3 on 2023-07-27 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiserverapplication", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bool",
            new_name="BooK",
        ),
    ]
