# Generated by Django 4.2.3 on 2023-07-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiserverapplication", "0002_rename_bool_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="descirption",
            new_name="description",
        ),
    ]
